version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    environment:
      - PORT=${PORT}
      - REDIS_URL=redis://redis:6379
      - CACHE_KEY=${CACHE_KEY}

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
